baseImageOverrides:
  github.com/imjasonh/kontain.me/cmd/api: gcr.io/buildpacks/builder
  github.com/imjasonh/kontain.me/cmd/buildpack: gcr.io/buildpacks/builder
  github.com/imjasonh/kontain.me/cmd/kaniko: gcr.io/kaniko-project/executor:v1.6.0-debug
  github.com/imjasonh/kontain.me/cmd/ko: golang
  github.com/imjasonh/kontain.me/cmd/viz: nixery.dev/graphviz
