name: Auto-Merge Dependabot

on:
  pull_request:
    branches: ['main']

jobs:
  auto-merge:
    name: Auto-Merge
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
