name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  ci:
    name: CI
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - run: go build ./...
